@startuml
title Aubie's Memory Game SSD
actor Player
participant Aubie
actor Memory

group SD: Aubie's Memory Game

    Player -> Aubie: start
    loop while !(gameOver)
        Player <-- Aubie:Board
        note right: UC: show Simon Board
        Player <-- Aubie:Controller
        Player <-- Aubie:Button
        note right: Note: index is set to score plus one
        loop while(index > 0)
            Player <-- Aubie:Random Button lights up
            note right: UC: flash sequence
            Player <-- Aubie:index decremented
        end
        loop while (player hits correct button)
            Player -> Aubie:hits button
            note right: UC: press button
            alt player hits wrong button
                Aubie --> Player: gameOver
            end
        end
        alt !gameOver
            Player <-- Aubie: score incremented
        end
    end
    Player -> Memory: score
    NOTE RIGHT: UC: publish score
end
@enduml